import type { Metadata } from "next";
import localFont from "next/font/local";
import { ModeToggle } from '@/components/ModeToggle'
import MainCardProps from "@/components/MainCardProps";
import { Toaster } from "@/components/ui/sonner"
import { BackgroundProvider } from '@/components/context/BackgroundContext'

import { ThemeProvider } from "@/components/providers/theme-provider"
// import { SignInButton, SignedIn, SignedOut, UserButton  } from '@clerk/nextjs'
import "./globals.css";
import DesignerContextProvider from "@/components/context/DesignerContext";
import NextTopLoader from "nextjs-toploader"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

          <MainCardProps>
          <NextTopLoader />
          <DesignerContextProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <nav className='flex justify-end border-b border-border h-[60px] px-4 py-2'>
            <ModeToggle />
        </nav>
        <main className='flex w-full flex-grow'>
            <BackgroundProvider>
            {children}
            </BackgroundProvider>
            
        </main>
        <Toaster />
        </ThemeProvider>
        </DesignerContextProvider>
        </MainCardProps>
        </body>
      </html>
  );
}
